# Generated by Django 4.2.1 on 2023-05-23 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ehms.articles.models
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleCategory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Title")),
                ("description", models.TextField(blank=True, max_length=5000, verbose_name="Description")),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="ctegory_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Category",
                "verbose_name_plural": "Article Categories",
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("title", models.CharField(max_length=254, unique=True, verbose_name="Title")),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="Published at")),
                ("published", models.BooleanField(default=False, verbose_name="Published")),
                ("excerpt", models.TextField(blank=True, max_length=500, verbose_name="Excerpt")),
                ("content", models.TextField(verbose_name="Content")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Article Sticky Big", "Article Sticky Big"),
                            ("Article Sticky Aside", "Article Sticky Aside"),
                            ("Article Other", "Article Other"),
                        ],
                        default="Article Other",
                        max_length=25,
                        verbose_name="Types",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ehms.articles.models.article_image_upload,
                        verbose_name="Article Image",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="article_Category",
                        to="articles.articlecategory",
                        verbose_name="Category",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="article_country",
                        to="addresses.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="article_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
                ("district", models.ManyToManyField(blank=True, to="addresses.district")),
                ("hospital", models.ManyToManyField(blank=True, to="hospitals.hospital")),
                ("region", models.ManyToManyField(blank=True, to="addresses.region")),
            ],
            options={
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
    ]
