# Generated by Django 4.2.1 on 2023-05-23 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ehms.practitioners.models
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Practitioner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("uid", models.CharField(blank=True, max_length=255, unique=True, verbose_name="UID")),
                ("first_name", models.CharField(max_length=100, verbose_name="First Name")),
                ("middle_name", models.CharField(blank=True, max_length=100, verbose_name="Middle Name")),
                ("last_name", models.CharField(blank=True, max_length=100, verbose_name="Last Name")),
                ("date_of_birth", models.DateField(blank=True, null=True, verbose_name="Date of Birth")),
                ("vital_status", models.BooleanField(default=True, verbose_name="Vital status")),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A Positive", "A Positive"),
                            ("O Positive", "O Positive"),
                            ("B Positive", "B Positive"),
                            ("AB Positive", "AB Positive"),
                            ("A Negative", "A Negative"),
                            ("O Negative", "O Negative"),
                            ("B Negative", "B Negative"),
                            ("AB Negative", "AB Negative"),
                        ],
                        max_length=50,
                        verbose_name="Blood group",
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Islam", "Islam"),
                            ("Christianity", "Christianity"),
                            ("Baha i Faith", "Baha i Faith"),
                            ("African Traditional Faith", "African Traditional Faith"),
                            ("Hinduism", "Hinduism"),
                            ("Buddhism", "Buddhism"),
                            ("Folk religions", "Folk religions"),
                            ("Sikhism", "Sikhism"),
                            ("Judaism", "Judaism"),
                            ("Others", "Others"),
                            ("No Religion", "No Religion"),
                        ],
                        max_length=50,
                        verbose_name="Religion",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female"), ("Transgender", "Transgender")],
                        max_length=11,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ehms.practitioners.models.practitioner_image_upload,
                        verbose_name="Practitioner Image",
                    ),
                ),
                ("email", models.EmailField(max_length=100, verbose_name="Email")),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                ("token", models.CharField(blank=True, max_length=8, null=True, verbose_name="Login token")),
                (
                    "token_timestamp",
                    models.DateTimeField(blank=True, default=None, null=True, verbose_name="Token timestamp"),
                ),
                ("verify_token", models.BooleanField(default=False)),
                ("phone", models.CharField(max_length=15, verbose_name="Phone")),
                ("alternate_phone", models.CharField(blank=True, max_length=15, verbose_name="Alternate phone")),
                ("address_line_1", models.CharField(max_length=200, verbose_name="Address Line 1")),
                ("address_line_2", models.CharField(blank=True, max_length=200, verbose_name="Address Line 2")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="addresses.country", verbose_name="Country"
                    ),
                ),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="practitioner_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="addresses.district", verbose_name="District"
                    ),
                ),
            ],
            options={
                "verbose_name": "Practitioner",
                "verbose_name_plural": "Practitioners",
            },
        ),
        migrations.CreateModel(
            name="PractitionerHospital",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("joined_on", models.DateField(verbose_name="Practitioner Joined on")),
                ("relieved_on", models.DateField(blank=True, null=True, verbose_name="Practitioner Relieved on")),
                ("designation", models.CharField(max_length=50, verbose_name="Designation")),
                ("current_hospital", models.BooleanField(default=False, verbose_name="Current hospital")),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="practitioner_hospital_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="practitioner_hospital",
                        to="hospitals.hospital",
                        verbose_name="Hospital",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="practitioner_hospital",
                        to="practitioners.practitioner",
                        verbose_name="Practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Practitioner Hospital Record",
                "verbose_name_plural": "Practitioner Hospital Records",
            },
        ),
        migrations.AddField(
            model_name="practitioner",
            name="hospital",
            field=models.ManyToManyField(through="practitioners.PractitionerHospital", to="hospitals.hospital"),
        ),
        migrations.AddField(
            model_name="practitioner",
            name="postcode",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="addresses.postcode", verbose_name="PostalCode"
            ),
        ),
        migrations.AddField(
            model_name="practitioner",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="addresses.region", verbose_name="Region"
            ),
        ),
        migrations.AddField(
            model_name="practitioner",
            name="town",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="addresses.town", verbose_name="Town"
            ),
        ),
    ]
