# Generated by Django 4.2.1 on 2023-05-23 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hospitals", "0001_initial"),
        ("practitioners", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PractitionerQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("subject", models.CharField(max_length=200, unique=True, verbose_name="Query")),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "attachment",
                    models.FileField(
                        blank=True, upload_to="hospitals/queries/attachments/", verbose_name="Attachment"
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In process", "In process"),
                            ("Rejected", "Rejected"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=10,
                        verbose_name="Response status",
                    ),
                ),
                ("response", models.TextField(blank=True, verbose_name="Response")),
                (
                    "creator_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="practitioner_query_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="hospitals.hospital", verbose_name="Hospital"
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="practitioners.practitioner",
                        verbose_name="Practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Practitioner Query",
                "verbose_name_plural": "Practitioner Queries",
            },
        ),
        migrations.CreateModel(
            name="HospitalQuery",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("subject", models.CharField(max_length=200, unique=True, verbose_name="Query")),
                ("body", models.TextField(verbose_name="Body")),
                (
                    "attachment",
                    models.FileField(
                        blank=True, upload_to="hospitals/queries/attachments/", verbose_name="Attachment"
                    ),
                ),
                (
                    "response_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("In process", "In process"),
                            ("Rejected", "Rejected"),
                            ("Completed", "Completed"),
                        ],
                        default="Pending",
                        max_length=10,
                        verbose_name="Response status",
                    ),
                ),
                ("response", models.TextField(blank=True, verbose_name="Response")),
                (
                    "creator_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="hospital_query_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="query_hospital",
                        to="hospitals.hospital",
                        verbose_name="Hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospital Query",
                "verbose_name_plural": "Hospital Queries",
            },
        ),
    ]
