# Generated by Django 4.2.1 on 2023-05-23 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ehms.patients.models
import model_utils.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("practitioners", "0001_initial"),
        ("hospitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Addiction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="addiction_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Addiction",
                "verbose_name_plural": "Addictions",
            },
        ),
        migrations.CreateModel(
            name="AgeGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Name")),
                ("range_from", models.IntegerField(blank=True, default=0, null=True, verbose_name="From")),
                ("range_to", models.IntegerField(blank=True, default=0, null=True, verbose_name="To")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="age_group_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Age Group",
                "verbose_name_plural": "Age Groups",
            },
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="allergy_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Allergy",
                "verbose_name_plural": "Allergies",
            },
        ),
        migrations.CreateModel(
            name="HealthStatus",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Name")),
                (
                    "css_class",
                    models.CharField(
                        help_text="Class name is associated with CSS styles.",
                        max_length=100,
                        verbose_name="Class Name",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="health_status_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Status",
                "verbose_name_plural": "Health Statuses",
            },
        ),
        migrations.CreateModel(
            name="MedicalIllness",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True, verbose_name="Name")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="medical_illness_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Illness",
                "verbose_name_plural": "Medical Illnesses",
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("uid", models.CharField(blank=True, max_length=255, unique=True, verbose_name="UID")),
                ("first_name", models.CharField(max_length=100, verbose_name="First Name")),
                ("middle_name", models.CharField(blank=True, max_length=100, verbose_name="Middle Name")),
                ("last_name", models.CharField(blank=True, max_length=100, verbose_name="Last Name")),
                ("date_of_birth", models.DateField(verbose_name="Date of Birth")),
                ("birth_time", models.TimeField(blank=True, null=True, verbose_name="Birth time")),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female"), ("Transgender", "Transgender")],
                        max_length=11,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "religion",
                    models.CharField(
                        choices=[
                            ("Islam", "Islam"),
                            ("Christianity", "Christianity"),
                            ("Baha i Faith", "Baha i Faith"),
                            ("African Traditional Faith", "African Traditional Faith"),
                            ("Hinduism", "Hinduism"),
                            ("Buddhism", "Buddhism"),
                            ("Folk religions", "Folk religions"),
                            ("Sikhism", "Sikhism"),
                            ("Judaism", "Judaism"),
                            ("Others", "Others"),
                            ("No Religion", "No Religion"),
                        ],
                        max_length=50,
                        verbose_name="Religion",
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Married", "Married"),
                            ("Unmarried", "Unmarried"),
                            ("Divorced", "Divorced"),
                            ("Widow", "Widow"),
                            ("Widower", "Widower"),
                        ],
                        max_length=10,
                        verbose_name="Marital status",
                    ),
                ),
                (
                    "pregnancy",
                    models.CharField(
                        choices=[
                            ("Pregnant", "Pregnant"),
                            ("Not Pregnant", "Not Pregnant"),
                            ("Not Applicable", "Not Applicable"),
                        ],
                        max_length=20,
                        verbose_name="Pregnancy status",
                    ),
                ),
                ("children", models.IntegerField(blank=True, default=0, verbose_name="Children")),
                ("email", models.EmailField(blank=True, max_length=100, null=True, verbose_name="Email")),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A Positive", "A Positive"),
                            ("O Positive", "O Positive"),
                            ("B Positive", "B Positive"),
                            ("AB Positive", "AB Positive"),
                            ("A Negative", "A Negative"),
                            ("O Negative", "O Negative"),
                            ("B Negative", "B Negative"),
                            ("AB Negative", "AB Negative"),
                        ],
                        max_length=50,
                        verbose_name="Blood group",
                    ),
                ),
                ("height", models.IntegerField(blank=True, null=True, verbose_name="Height (in cm)")),
                ("weight", models.IntegerField(blank=True, null=True, verbose_name="Weight (in kg)")),
                ("disability", models.BooleanField(default=False, verbose_name="Disability, if any?")),
                ("temporary_family_info", models.TextField(blank=True, verbose_name="Temporary family information")),
                ("bcg", models.BooleanField(default=False, verbose_name="BCG vaccination")),
                ("pentavalent", models.BooleanField(default=False, verbose_name="Pentavalent vaccination")),
                ("pneumo", models.BooleanField(default=False, verbose_name="Pneumo vaccination")),
                ("polio", models.BooleanField(default=False, verbose_name="Polio vaccination")),
                ("rotarix", models.BooleanField(default=False, verbose_name="Rotarix vaccination")),
                ("measles_rubella_1", models.BooleanField(default=False, verbose_name="Measles Rubella first dose")),
                ("measles_rubella_2", models.BooleanField(default=False, verbose_name="Measles Rubella second dose")),
                ("dpt", models.BooleanField(default=False, verbose_name="DPT vaccination")),
                ("yellow_fever", models.BooleanField(default=False, verbose_name="Yellow Fever vaccination")),
                ("vitamin_a", models.BooleanField(default=False, verbose_name="Vitamin A vaccination")),
                ("tetanus", models.BooleanField(default=False, verbose_name="Tetanus vaccination")),
                ("tt_one_pregnant", models.BooleanField(default=False, verbose_name="TT1 vaccination")),
                ("tt_two_pregnant", models.BooleanField(default=False, verbose_name="TT2 vaccination")),
                ("tt_booster", models.BooleanField(default=False, verbose_name="TT Booster")),
                ("other_information", models.TextField(blank=True, verbose_name="Extra information")),
                ("remarks", models.TextField(blank=True, verbose_name="Remarks")),
                ("vital_status", models.BooleanField(default=True, verbose_name="Vital status")),
                ("voter_card_number", models.CharField(blank=True, max_length=100)),
                (
                    "age_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_age_group",
                        to="patients.agegroup",
                        verbose_name="Age Group",
                    ),
                ),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
                (
                    "health_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_health_status",
                        to="patients.healthstatus",
                        verbose_name="Health Status",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_hospital",
                        to="hospitals.hospital",
                        verbose_name="Hospital",
                    ),
                ),
                (
                    "patient_addictions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="patient_addictions",
                        to="patients.addiction",
                        verbose_name="Patient addictions",
                    ),
                ),
                (
                    "patient_allergies",
                    models.ManyToManyField(
                        blank=True,
                        related_name="patient_medical_allergies",
                        to="patients.allergy",
                        verbose_name="Patient medical allergies",
                    ),
                ),
                (
                    "patient_kin_medical_illness",
                    models.ManyToManyField(
                        blank=True,
                        related_name="patient_kin_medical_illness",
                        to="patients.medicalillness",
                        verbose_name="Patient kin medical illness",
                    ),
                ),
                (
                    "patient_medical_illness",
                    models.ManyToManyField(
                        blank=True,
                        related_name="patient_medical_illness",
                        to="patients.medicalillness",
                        verbose_name="Patient medical illness",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.CreateModel(
            name="PatientImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=ehms.patients.models.patient_image_upload,
                        verbose_name="Patient Image",
                    ),
                ),
                ("current_image", models.BooleanField(default=False, verbose_name="Current image")),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_image_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_image_hospital",
                        to="hospitals.hospital",
                        verbose_name="Hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_image",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Image",
                "verbose_name_plural": "Patients Image",
            },
        ),
        migrations.CreateModel(
            name="PatientDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("type", models.CharField(max_length=255, verbose_name="Type")),
                ("document", models.FileField(upload_to="patient_document_upload", verbose_name="Document file")),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_document_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_document_hospital",
                        to="hospitals.hospital",
                        verbose_name="Hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_document",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Document",
                "verbose_name_plural": "Patient Documents",
            },
        ),
        migrations.CreateModel(
            name="PatientDeathRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                (
                    "died_on",
                    models.DateTimeField(default=django.utils.timezone.now, verbose_name="Patient death date"),
                ),
                ("reason", models.TextField(verbose_name="Reason of death")),
                ("place", models.CharField(max_length=200, verbose_name="Place where patient died")),
                ("notes", models.TextField(blank=True, max_length=20000, verbose_name="Extra information (notes)")),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_death_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_death_hospital",
                        to="hospitals.hospital",
                        verbose_name="Hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_died",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "practitioner",
                    models.ForeignKey(
                        help_text="Practitioner attended or declare the patient/dead.",
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_death_practitioner",
                        to="practitioners.practitioner",
                        verbose_name="Practitioner",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Death Record",
                "verbose_name_plural": "Patient Death Record",
            },
        ),
        migrations.CreateModel(
            name="PatientAddress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                (
                    "address_line_1",
                    models.CharField(
                        help_text="e.g. Flat No or House No ...", max_length=250, verbose_name="Address Line 1"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True,
                        help_text="Extra information related to address e.g. landmark ...",
                        max_length=250,
                        verbose_name="Address Line 2",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="Email")),
                ("phone", models.CharField(blank=True, max_length=12, verbose_name="Phone")),
                ("alternate_phone", models.CharField(blank=True, max_length=12, verbose_name="Alternate Phone")),
                (
                    "type",
                    models.CharField(
                        choices=[("Temporary", "Temporary"), ("Permanent", "Permanent")],
                        default="Permanent",
                        max_length=10,
                        verbose_name="Type",
                    ),
                ),
                ("current_address", models.BooleanField(default=False, verbose_name="Is this your current address?")),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_country",
                        to="addresses.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "creator_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_address_creator_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged in user",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_district",
                        to="addresses.district",
                        verbose_name="District",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="address_recorded_in_hospital",
                        to="hospitals.hospital",
                        verbose_name="Hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_belong_to_address",
                        to="patients.patient",
                        verbose_name="Patient",
                    ),
                ),
                (
                    "postcode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_postcode",
                        to="addresses.postcode",
                        verbose_name="PostalCode",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_region",
                        to="addresses.region",
                        verbose_name="Region",
                    ),
                ),
                (
                    "town",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="patient_town",
                        to="addresses.town",
                        verbose_name="Town",
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Address",
                "verbose_name_plural": "Patient Addresses",
            },
        ),
    ]
